name: x86-Ubuntu

on:
  push:
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main"
          sudo apt-get update
          sudo apt-get install -y llvm-14 llvm-14-dev libllvm14 clang-14 libclang-common-14-dev libclang-14-dev llvm-14-tools libomp-14-dev libmlir-14 libmlir-14-dev
          sudo apt-get install python3-setuptools
          sudo pip3 install lit
      - name: Build HelloWorld
        run: |
          cd HelloWorld
          mkdir build && cd build
          # HelloWorld only supports CT_Clang_INSTALL_DIR
          cmake -DCT_Clang_INSTALL_DIR=/usr/lib/llvm-14/ ../
          make -j2
          /usr/lib/llvm-14/bin/clang -cc1 -load ./libHelloWorld.so -plugin hello-world $GITHUB_WORKSPACE/test/HelloWorld-basic.cpp
      - name: Build clang-tutor + run tests
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          # Test with Clang_ROOT
          cmake -DClang_ROOT=/usr/lib/llvm-14/lib/cmake/clang/ ../
          make -j2
          lit test/
