name: x86-Darwin

on: 
  push:
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        type: [Debug, Release]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          brew update
          brew install llvm
          pip3 install lit
      - name: Build HelloWorld
        run: |
          cd HelloWorld
          mkdir build && cd build
          cmake -DCT_Clang_INSTALL_DIR=/usr/local/opt/llvm/ ../
          make -j2
          /usr/local/opt/llvm/bin/clang -cc1 -load ./libHelloWorld.dylib -plugin hello-world $GITHUB_WORKSPACE/test/HelloWorld-basic.cpp
      - name: Build clang-tutor + run tests
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DCT_Clang_INSTALL_DIR=/usr/local/opt/llvm/ -DCMAKE_BUILD_TYPE=${{ matrix.type }}  ../
          make -j2
          lit test/
