name: x86-Darwin-llvm-from-sources

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download Ninja
        run: |
          git clone https://github.com/ninja-build/ninja.git
          pushd ninja
          ./configure.py --bootstrap
          popd
      - name: Add Ninja to $PATH
        run: |
          echo "${GITHUB_WORKSPACE}/ninja" >> $GITHUB_PATH
      - name: Clone llvm-project
        run: |
          git clone --depth 1 --single-branch --branch release/14.x https://github.com/llvm/llvm-project
      - name: Build LLVM & Clang
        run: |
          cd llvm-project
          git checkout release/14.x
          mkdir build && cd build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;libcxx;libcxxabi" \
            -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_OPTIMIZED_TABLEGEN=ON \
            -DDEFAULT_SYSROOT="$(xcrun --show-sdk-path)" \
            ../llvm
          ninja
      - name: Install lit
        run: |
          sudo pip3 install lit
      - name: Build HelloWorld
        run: |
          cd HelloWorld
          mkdir build && cd build
          cmake -DCT_Clang_INSTALL_DIR="$GITHUB_WORKSPACE/llvm-project/build" ../
          make -j2
      - name: Build clang-tutor + run tests
        run: |
          mkdir build && cd build
          cmake -DCT_Clang_INSTALL_DIR="$GITHUB_WORKSPACE/llvm-project/build" ../
          make -j2
          lit -va test/
